### ISSUE TITLE
docs: add quickstart example of API

### ISSUE THREAD

**Issue by bcoe** [googleapis/nodejs-datalabeling#44]
we should add a `samples/quickstart.js` demonstrating how to use the API.

**Comment by grant** [comment]
Looks like the `samples/` folder contains files that are empty? Very misguiding...

https://github.com/googleapis/nodejs-datalabeling/blob/master/samples/quickstart.js

Bug bashing:
b/134740085

**Comment by bcoe** [comment]
fixed by https://github.com/googleapis/nodejs-datalabeling/pull/88
